-- 兼容《Cost_Data_Cost_Sales_Nospecialty_JJRC 经营预测普药非新特药计算.sql》
-- 中 INSERT INTO mis_auto_jyycmx(...) 的字段清单。
-- srcid 已存在于 public.mis_auto_jyycmx，当前类型为 varchar，这里不重复新增。
-- 如果后续要原样执行普药提供过程里的 i.srcid = ptpcr.id 这类关联，
-- 建议先确认 srcid 全部为数字，再按需把 srcid 改为 integer：
-- ALTER TABLE public.mis_auto_jyycmx
--     ALTER COLUMN srcid TYPE integer USING NULLIF(srcid, '')::integer;

ALTER TABLE public.mis_auto_jyycmx
    ADD COLUMN IF NOT EXISTS orderno varchar,
    ADD COLUMN IF NOT EXISTS cperiod varchar,
    ADD COLUMN IF NOT EXISTS fapiaoqijian varchar,
    ADD COLUMN IF NOT EXISTS csaleinvoiceid varchar,
    ADD COLUMN IF NOT EXISTS csaleinvoicecode varchar,
    ADD COLUMN IF NOT EXISTS cinvoicecustid varchar,
    ADD COLUMN IF NOT EXISTS firstvbillcode varchar,
    ADD COLUMN IF NOT EXISTS vdef__1 varchar,
    ADD COLUMN IF NOT EXISTS vdef__2 varchar,
    ADD COLUMN IF NOT EXISTS vdef__3 varchar,
    ADD COLUMN IF NOT EXISTS name_2 varchar,
    ADD COLUMN IF NOT EXISTS name_5 varchar,
    ADD COLUMN IF NOT EXISTS area_class2 varchar,
    ADD COLUMN IF NOT EXISTS name_6 varchar,
    ADD COLUMN IF NOT EXISTS sales_channel varchar,
    ADD COLUMN IF NOT EXISTS sales_channep varchar,
    ADD COLUMN IF NOT EXISTS area_class varchar,
    ADD COLUMN IF NOT EXISTS area_name2 varchar,
    ADD COLUMN IF NOT EXISTS vbillcode varchar,
    ADD COLUMN IF NOT EXISTS vdef__5 varchar,
    ADD COLUMN IF NOT EXISTS drugstype varchar,
    ADD COLUMN IF NOT EXISTS cmaterialvid varchar,
    ADD COLUMN IF NOT EXISTS material_code varchar,
    ADD COLUMN IF NOT EXISTS material_name varchar,
    ADD COLUMN IF NOT EXISTS material_spec varchar,
    ADD COLUMN IF NOT EXISTS nnum numeric(24,8),
    ADD COLUMN IF NOT EXISTS quantity numeric(24,8),
    ADD COLUMN IF NOT EXISTS norigtaxprice1 numeric(24,8),
    ADD COLUMN IF NOT EXISTS norigtaxnetprice numeric(24,8),
    ADD COLUMN IF NOT EXISTS norigmny1 numeric(24,8),
    ADD COLUMN IF NOT EXISTS ntotalincomemny numeric(24,8),
    ADD COLUMN IF NOT EXISTS norigsubmny1 numeric(24,8),
    ADD COLUMN IF NOT EXISTS ntotalincomemny1 numeric(24,8),
    ADD COLUMN IF NOT EXISTS norigdiscount1 numeric(24,8),
    ADD COLUMN IF NOT EXISTS cdq_je_bhs numeric(24,8),
    ADD COLUMN IF NOT EXISTS unitbaseprice numeric(24,8),
    ADD COLUMN IF NOT EXISTS minimumpriceamount numeric(24,8),
    ADD COLUMN IF NOT EXISTS rowpknum integer,
    ADD COLUMN IF NOT EXISTS status tinyint,
    ADD COLUMN IF NOT EXISTS companyid integer,
    ADD COLUMN IF NOT EXISTS createid integer,
    ADD COLUMN IF NOT EXISTS allnode varchar,
    ADD COLUMN IF NOT EXISTS createtime integer,
    ADD COLUMN IF NOT EXISTS isVoid tinyint;

-- 兼容同一过程后续 UPDATE 以及 levels3 跨期票折回写字段。
ALTER TABLE public.mis_auto_jyycmx
    ADD COLUMN IF NOT EXISTS dingdanchongdijine numeric(24,8),
    ADD COLUMN IF NOT EXISTS dingdanshuliang numeric(24,8),
    ADD COLUMN IF NOT EXISTS fpwlhzchongdijine numeric(24,8),
    ADD COLUMN IF NOT EXISTS fpwlhzshuliang numeric(24,8),
    ADD COLUMN IF NOT EXISTS dangqipiaozhefentand numeric(24,8),
    ADD COLUMN IF NOT EXISTS dq_pz numeric(24,8),
    ADD COLUMN IF NOT EXISTS sw_lpz_sr numeric(24,8),
    ADD COLUMN IF NOT EXISTS lpz_sr_hj numeric(24,8),
    ADD COLUMN IF NOT EXISTS sw_lpz_sr_hj numeric(24,8),
    ADD COLUMN IF NOT EXISTS js_lpz_fy numeric(24,8),
    ADD COLUMN IF NOT EXISTS zs_lpz_fy numeric(24,8),
    ADD COLUMN IF NOT EXISTS bhdq_pz_cdq_bhs numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_ftamount varchar,
    ADD COLUMN IF NOT EXISTS fdq_ftnum varchar,
    ADD COLUMN IF NOT EXISTS fdq_pz numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_bcdq numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdqb_ftamount varchar,
    ADD COLUMN IF NOT EXISTS fdqb_ftnum varchar,
    ADD COLUMN IF NOT EXISTS fdq_pz_jt numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_bcdq_jt numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_hj numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_bcdq_hj numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_bcdq_bhs numeric(24,8),
    ADD COLUMN IF NOT EXISTS fdq_pz_bhs numeric(24,8),
    ADD COLUMN IF NOT EXISTS pz_hj numeric(24,8);
